[package]
name = "simonnote"
version = "1.0.0"
edition = "2021"
description = "A fast, minimal note-taking app for GNOME written in Rust"
license = "MIT OR Apache-2.0"
repository = "https://github.com/simonpagl47-cpu/Simon-Note-Linux"

[dependencies]
gtk4 = { version = "0.11", features = ["v4_14"] }
adw = { package = "libadwaita", version = "0.9", features = ["v1_5"] }
gio = { version = "0.22", features = ["v2_80"] }
glib = { version = "0.22", features = ["v2_80"] }
gdk4 = { version = "0.11", features = ["v4_14"] }
pango = { version = "0.22" }
memchr = "2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

[workspace]